var files = ["0.0_high school_married, spouse present_male_white non-hispanic_.json",
"0.0_high school_married, spouse present_female_white non-hispanic_.json",
"0.0_some college, no degree_married, spouse present_female_white non-hispanic_.json",
"0.0_high school_never married_male_white non-hispanic_.json",
"0.0_bachelors_married, spouse present_female_white non-hispanic_.json",
"0.0_high school_widowed or divorced_female_white non-hispanic_.json",
"0.0_some college, no degree_never married_male_white non-hispanic_.json",
"0.0_bachelors_married, spouse present_male_white non-hispanic_.json",
"0.0_less than 12th grade_never married_male_white non-hispanic_.json",
"0.0_some college, no degree_married, spouse present_male_white non-hispanic_.json",
"0.0_grad school_married, spouse present_male_white non-hispanic_.json",
"0.0_bachelors_never married_male_white non-hispanic_.json",
"0.0_some college, no degree_never married_female_white non-hispanic_.json",
"0.0_bachelors_never married_female_white non-hispanic_.json",
"0.0_grad school_married, spouse present_female_white non-hispanic_.json",
"0.0_high school_never married_female_white non-hispanic_.json",
"0.0_less than 12th grade_married, spouse present_male_white non-hispanic_.json",
"0.0_high school_widowed or divorced_male_white non-hispanic_.json",
"0.0_less than 12th grade_never married_female_white non-hispanic_.json",
"0.0_high school_never married_male_black non-hispanic_.json",
"0.0_less than 12th grade_married, spouse present_female_white non-hispanic_.json",
"0.0_high school_never married_female_black non-hispanic_.json",
"0.0_less than 12th grade_never married_male_hispanic_.json",
"0.0_some college, no degree_widowed or divorced_female_white non-hispanic_.json",
"0.0_some college, no degree_widowed or divorced_male_white non-hispanic_.json",
"0.0_less than 12th grade_married, spouse present_female_hispanic_.json",
"0.0_less than 12th grade_married, spouse present_male_hispanic_.json",
"0.0_bachelors_widowed or divorced_female_white non-hispanic_.json",
"0.0_high school_married, spouse present_male_black non-hispanic_.json",
"0.0_high school_married, spouse present_female_hispanic_.json",
"0.0_bachelors_widowed or divorced_male_white non-hispanic_.json",
"0.0_associates-academic_married, spouse present_female_white non-hispanic_.json",
"0.0_less than 12th grade_widowed or divorced_female_white non-hispanic_.json",
"0.0_less than 12th grade_never married_female_hispanic_.json",
"0.0_associates-vocational_married, spouse present_female_white non-hispanic_.json",
"0.0_high school_married, spouse present_female_black non-hispanic_.json",
"0.0_associates-vocational_married, spouse present_male_white non-hispanic_.json",
"0.0_some college, no degree_never married_female_black non-hispanic_.json",
"0.0_high school_widowed or divorced_female_black non-hispanic_.json",
"0.0_less than 12th grade_widowed or divorced_male_white non-hispanic_.json",
"0.0_high school_never married_male_hispanic_.json",
"0.0_high school_never married_female_hispanic_.json",
"0.0_some college, no degree_never married_male_black non-hispanic_.json",
"0.0_grad school_widowed or divorced_female_white non-hispanic_.json",
"0.0_less than 12th grade_never married_male_black non-hispanic_.json",
"0.0_high school_married, spouse present_male_hispanic_.json",
"0.0_associates-academic_married, spouse present_male_white non-hispanic_.json",
"0.0_associates-vocational_widowed or divorced_female_white non-hispanic_.json",
"0.0_high school_married, spouse present_female_other non-hispanic_.json",
"0.0_high school_separated_female_white non-hispanic_.json",
"0.0_less than 12th grade_never married_female_black non-hispanic_.json",
"0.0_high school_never married_male_other non-hispanic_.json",
"0.0_some college, no degree_never married_male_hispanic_.json",
"0.0_associates-academic_widowed or divorced_female_white non-hispanic_.json",
"0.0_grad school_never married_female_white non-hispanic_.json",
"0.0_some college, no degree_never married_female_hispanic_.json",
"0.0_grad school_widowed or divorced_male_white non-hispanic_.json",
"0.0_high school_married, spouse present_male_other non-hispanic_.json",
"0.0_grad school_never married_male_white non-hispanic_.json",
"0.0_high school_separated_male_white non-hispanic_.json",
"0.0_bachelors_married, spouse present_female_other non-hispanic_.json",
"0.0_associates-vocational_never married_male_white non-hispanic_.json",
"0.0_associates-academic_never married_male_white non-hispanic_.json",
"0.0_some college, no degree_never married_male_other non-hispanic_.json",
"0.0_some college, no degree_widowed or divorced_female_black non-hispanic_.json",
"0.0_less than 12th grade_never married_male_other non-hispanic_.json",
"0.0_associates-academic_never married_female_white non-hispanic_.json",
"0.0_some college, no degree_married, spouse present_male_black non-hispanic_.json",
"0.0_bachelors_never married_female_black non-hispanic_.json",
"0.0_high school_widowed or divorced_female_hispanic_.json",
"0.0_high school_widowed or divorced_male_black non-hispanic_.json",
"0.0_some college, no degree_married, spouse present_female_hispanic_.json",
"0.0_some college, no degree_married, spouse present_female_black non-hispanic_.json",
"0.0_associates-vocational_never married_female_white non-hispanic_.json",
"0.0_some college, no degree_married, spouse present_male_hispanic_.json",
"0.0_less than 12th grade_widowed or divorced_female_hispanic_.json",
"0.0_bachelors_never married_male_other non-hispanic_.json",
"0.0_associates-vocational_widowed or divorced_male_white non-hispanic_.json",
"0.0_bachelors_married, spouse present_male_other non-hispanic_.json",
"0.0_some college, no degree_never married_female_other non-hispanic_.json",
"0.0_high school_never married_female_other non-hispanic_.json",
"0.0_less than 12th grade_never married_female_other non-hispanic_.json",
"0.0_bachelors_never married_male_black non-hispanic_.json",
"0.0_some college, no degree_separated_female_white non-hispanic_.json",
"0.0_bachelors_married, spouse present_female_black non-hispanic_.json",
"0.0_grad school_married, spouse present_male_other non-hispanic_.json",
"0.0_bachelors_never married_female_other non-hispanic_.json",
"0.0_bachelors_married, spouse present_female_hispanic_.json",
"0.0_associates-academic_widowed or divorced_male_white non-hispanic_.json",
"0.0_bachelors_married, spouse present_male_black non-hispanic_.json",
"0.0_less than 12th grade_married, spouse present_male_black non-hispanic_.json",
"0.0_high school_widowed or divorced_male_hispanic_.json",
"0.0_some college, no degree_married, spouse present_female_other non-hispanic_.json",
"0.0_high school_separated_female_black non-hispanic_.json",
"0.0_less than 12th grade_separated_male_hispanic_.json",
"0.0_some college, no degree_married, spouse present_male_other non-hispanic_.json",
"0.0_some college, no degree_separated_male_white non-hispanic_.json",
"0.0_high school_separated_male_black non-hispanic_.json",
"0.0_bachelors_married, spouse present_male_hispanic_.json",
"0.0_less than 12th grade_separated_female_hispanic_.json",
"0.0_less than 12th grade_separated_male_white non-hispanic_.json",
"0.0_some college, no degree_widowed or divorced_male_black non-hispanic_.json",
"0.0_bachelors_never married_male_hispanic_.json",
"0.0_high school_separated_female_hispanic_.json",
"0.0_less than 12th grade_widowed or divorced_female_black non-hispanic_.json",
"0.0_bachelors_never married_female_hispanic_.json",
"0.0_less than 12th grade_separated_female_white non-hispanic_.json",
"0.0_bachelors_separated_male_white non-hispanic_.json",
"0.0_less than 12th grade_widowed or divorced_male_hispanic_.json",
"0.0_less than 12th grade_married, spouse present_male_other non-hispanic_.json",
"0.0_grad school_married, spouse present_female_other non-hispanic_.json",
"0.0_less than 12th grade_married, spouse present_female_black non-hispanic_.json",
"0.0_bachelors_widowed or divorced_female_black non-hispanic_.json",
"0.0_high school_widowed or divorced_female_other non-hispanic_.json",
"0.0_less than 12th grade_widowed or divorced_male_black non-hispanic_.json",
"0.0_high school_separated_male_hispanic_.json",
"0.0_high school_widowed or divorced_male_other non-hispanic_.json",
"0.0_less than 12th grade_married, spouse present_female_other non-hispanic_.json",
"0.0_some college, no degree_widowed or divorced_female_hispanic_.json",
"0.0_some college, no degree_separated_female_black non-hispanic_.json",
"0.0_associates-vocational_never married_female_black non-hispanic_.json",
"0.0_bachelors_separated_female_white non-hispanic_.json",
"0.0_associates-academic_never married_female_black non-hispanic_.json",
"0.0_less than 12th grade_separated_female_black non-hispanic_.json",
"0.0_some college, no degree_separated_male_black non-hispanic_.json",
"0.0_less than 12th grade_separated_male_black non-hispanic_.json",
"0.0_grad school_never married_female_black non-hispanic_.json",
"0.0_some college, no degree_widowed or divorced_female_other non-hispanic_.json",
"0.0_associates-vocational_never married_male_black non-hispanic_.json",
"0.0_some college, no degree_widowed or divorced_male_hispanic_.json",
"0.0_associates-academic_never married_male_black non-hispanic_.json",
"0.0_grad school_married, spouse present_male_black non-hispanic_.json",
"0.0_grad school_married, spouse present_female_black non-hispanic_.json",
"0.0_associates-vocational_married, spouse present_female_hispanic_.json",
"0.0_bachelors_widowed or divorced_female_other non-hispanic_.json",
"0.0_some college, no degree_widowed or divorced_male_other non-hispanic_.json",
"0.0_bachelors_widowed or divorced_male_black non-hispanic_.json",
"0.0_grad school_never married_male_other non-hispanic_.json",
"0.0_associates-vocational_married, spouse present_male_black non-hispanic_.json",
"0.0_associates-academic_widowed or divorced_female_black non-hispanic_.json",
"0.0_grad school_married, spouse present_male_hispanic_.json",
"0.0_high school_separated_male_other non-hispanic_.json",
"0.0_bachelors_widowed or divorced_female_hispanic_.json",
"0.0_associates-academic_married, spouse present_female_hispanic_.json",
"0.0_grad school_widowed or divorced_female_black non-hispanic_.json",
"0.0_associates-academic_married, spouse present_female_black non-hispanic_.json",
"1.0_high school_married, spouse present_female_white non-hispanic_.json",
"0.0_associates-academic_married, spouse present_male_black non-hispanic_.json",
"0.0_associates-vocational_widowed or divorced_female_black non-hispanic_.json",
"0.0_grad school_never married_female_other non-hispanic_.json",
"0.0_some college, no degree_separated_female_hispanic_.json",
"0.0_bachelors_married, armed forces spouse present_female_white non-hispanic_.json",
"0.0_grad school_separated_male_white non-hispanic_.json",
"1.0_some college, no degree_married, spouse present_female_white non-hispanic_.json",
"0.0_associates-academic_never married_male_hispanic_.json",
"0.0_high school_separated_female_other non-hispanic_.json",
"0.0_associates-vocational_married, spouse present_male_other non-hispanic_.json",
"1.0_bachelors_married, spouse present_female_white non-hispanic_.json",
"0.0_associates-vocational_married, spouse present_female_black non-hispanic_.json",
"0.0_associates-academic_married, spouse present_female_other non-hispanic_.json",
"0.0_grad school_married, spouse present_female_hispanic_.json",
"0.0_some college, no degree_married, armed forces spouse present_female_white non-hispanic_.json",
"0.0_grad school_never married_male_black non-hispanic_.json",
"0.0_associates-academic_separated_female_white non-hispanic_.json",
"0.0_grad school_separated_female_white non-hispanic_.json",
"1.0_high school_married, spouse present_male_white non-hispanic_.json",
"1.0_high school_never married_female_white non-hispanic_.json",
"0.0_high school_married, armed forces spouse present_female_white non-hispanic_.json",
"0.0_less than 12th grade_widowed or divorced_female_other non-hispanic_.json",
"0.0_associates-vocational_separated_female_white non-hispanic_.json",
"1.0_high school_never married_male_white non-hispanic_.json",
"0.0_associates-academic_never married_female_hispanic_.json",
"1.0_less than 12th grade_married, spouse present_male_hispanic_.json",
"2.0_bachelors_married, spouse present_female_white non-hispanic_.json",
"1.0_some college, no degree_married, spouse present_male_white non-hispanic_.json",
"0.0_associates-vocational_married, spouse present_male_hispanic_.json",
"2.0_high school_married, spouse present_male_white non-hispanic_.json",
"0.0_associates-academic_never married_male_other non-hispanic_.json",
"2.0_high school_married, spouse present_female_white non-hispanic_.json",
"1.0_high school_never married_female_black non-hispanic_.json",
"1.0_bachelors_married, spouse present_male_white non-hispanic_.json",
"0.0_less than 12th grade_widowed or divorced_male_other non-hispanic_.json",
"1.0_less than 12th grade_married, spouse present_female_hispanic_.json",
"1.0_some college, no degree_never married_female_white non-hispanic_.json",
"0.0_associates-academic_married, spouse present_male_other non-hispanic_.json",
"1.0_less than 12th grade_never married_female_white non-hispanic_.json",
"1.0_high school_married, spouse present_male_hispanic_.json",
"1.0_high school_married, spouse present_female_hispanic_.json",
"1.0_less than 12th grade_never married_female_black non-hispanic_.json",
"0.0_associates-vocational_never married_female_hispanic_.json",
"1.0_less than 12th grade_never married_male_white non-hispanic_.json",
"0.0_associates-vocational_never married_male_other non-hispanic_.json",
"1.0_less than 12th grade_never married_female_hispanic_.json",
"1.0_grad school_married, spouse present_female_white non-hispanic_.json",
"1.0_less than 12th grade_never married_male_hispanic_.json",
"1.0_high school_never married_male_black non-hispanic_.json",
"1.0_some college, no degree_never married_female_black non-hispanic_.json",
"1.0_high school_never married_female_hispanic_.json",
"1.0_less than 12th grade_married, spouse present_male_white non-hispanic_.json",
"1.0_high school_widowed or divorced_female_white non-hispanic_.json",
"2.0_high school_never married_female_black non-hispanic_.json",
"0.0_associates-vocational_separated_male_white non-hispanic_.json",
"0.0_associates-academic_married, spouse present_male_hispanic_.json",
"0.0_associates-vocational_married, spouse present_female_other non-hispanic_.json",
"2.0_some college, no degree_married, spouse present_female_white non-hispanic_.json",
"2.0_high school_never married_female_white non-hispanic_.json",
"1.0_high school_never married_male_hispanic_.json",
"0.0_associates-vocational_never married_male_hispanic_.json",
"2.0_some college, no degree_married, spouse present_male_white non-hispanic_.json",
"1.0_high school_married, spouse present_male_black non-hispanic_.json",
"1.0_less than 12th grade_never married_male_black non-hispanic_.json",
"1.0_associates-academic_married, spouse present_female_white non-hispanic_.json",
"1.0_grad school_married, spouse present_male_white non-hispanic_.json",
"2.0_bachelors_married, spouse present_male_white non-hispanic_.json",
"2.0_less than 12th grade_never married_female_hispanic_.json",
"0.0_associates-academic_never married_female_other non-hispanic_.json",
"1.0_some college, no degree_widowed or divorced_female_white non-hispanic_.json",
"2.0_less than 12th grade_never married_male_hispanic_.json",
"1.0_some college, no degree_married, spouse present_female_hispanic_.json",
"0.0_bachelors_separated_female_black non-hispanic_.json",
"0.0_bachelors_widowed or divorced_male_other non-hispanic_.json",
"2.0_less than 12th grade_never married_female_black non-hispanic_.json",
"1.0_associates-vocational_married, spouse present_female_white non-hispanic_.json",
"1.0_high school_widowed or divorced_male_white non-hispanic_.json",
"0.0_some college, no degree_separated_male_hispanic_.json",
"1.0_high school_married, spouse present_female_black non-hispanic_.json",
"1.0_high school_separated_female_white non-hispanic_.json",
"1.0_some college, no degree_never married_female_hispanic_.json",
"1.0_some college, no degree_never married_male_white non-hispanic_.json",
"1.0_less than 12th grade_married, spouse present_female_white non-hispanic_.json",
"2.0_less than 12th grade_never married_female_white non-hispanic_.json",
"1.0_high school_married, spouse present_male_other non-hispanic_.json",
"2.0_less than 12th grade_married, spouse present_male_hispanic_.json",
"1.0_high school_never married_female_other non-hispanic_.json",
"0.0_associates-vocational_widowed or divorced_female_hispanic_.json",
"2.0_high school_married, spouse present_female_hispanic_.json",
"2.0_high school_never married_male_white non-hispanic_.json",
"2.0_high school_never married_female_hispanic_.json",
"0.0_bachelors_widowed or divorced_male_hispanic_.json",
"2.0_less than 12th grade_never married_male_white non-hispanic_.json",
"0.0_grad school_widowed or divorced_female_other non-hispanic_.json",
"0.0_grad school_never married_male_hispanic_.json",
"2.0_some college, no degree_never married_female_black non-hispanic_.json",
"0.0_associates-academic_separated_male_white non-hispanic_.json",
"2.0_less than 12th grade_married, spouse present_female_hispanic_.json",
"1.0_high school_never married_male_other non-hispanic_.json",
"0.0_associates-academic_widowed or divorced_male_black non-hispanic_.json",
"0.0_grad school_never married_female_hispanic_.json",
"0.0_grad school_widowed or divorced_male_black non-hispanic_.json",
"1.0_associates-vocational_married, spouse present_male_white non-hispanic_.json",
"0.0_associates-vocational_widowed or divorced_male_black non-hispanic_.json",
"0.0_associates-academic_widowed or divorced_female_other non-hispanic_.json",
"1.0_some college, no degree_married, spouse present_female_black non-hispanic_.json",
"1.0_less than 12th grade_separated_female_hispanic_.json",
"2.0_high school_never married_male_black non-hispanic_.json",
"1.0_some college, no degree_married, spouse present_male_black non-hispanic_.json",
"1.0_some college, no degree_never married_male_black non-hispanic_.json",
"0.0_bachelors_separated_male_black non-hispanic_.json",
"1.0_high school_married, spouse present_female_other non-hispanic_.json",
"0.0_some college, no degree_separated_female_other non-hispanic_.json",
"2.0_less than 12th grade_married, spouse present_male_white non-hispanic_.json",
"0.0_associates-academic_widowed or divorced_female_hispanic_.json",
"2.0_high school_married, spouse present_male_hispanic_.json",
"1.0_less than 12th grade_widowed or divorced_female_white non-hispanic_.json",
"2.0_high school_widowed or divorced_female_white non-hispanic_.json",
"1.0_high school_widowed or divorced_female_black non-hispanic_.json",
"1.0_some college, no degree_married, spouse present_male_hispanic_.json",
"1.0_some college, no degree_separated_female_white non-hispanic_.json",
"2.0_grad school_married, spouse present_female_white non-hispanic_.json",
"1.0_less than 12th grade_never married_male_other non-hispanic_.json",
"1.0_associates-academic_married, spouse present_male_white non-hispanic_.json",
"1.0_high school_separated_female_black non-hispanic_.json",
"1.0_high school_separated_female_hispanic_.json",
"2.0_high school_married, spouse present_male_black non-hispanic_.json",
"1.0_bachelors_married, spouse present_female_other non-hispanic_.json",
"2.0_some college, no degree_never married_female_white non-hispanic_.json",
"0.0_less than 12th grade_separated_female_other non-hispanic_.json",
"2.0_less than 12th grade_married, spouse present_female_white non-hispanic_.json",
"1.0_less than 12th grade_never married_female_other non-hispanic_.json",
"1.0_bachelors_married, spouse present_female_hispanic_.json",
"1.0_some college, no degree_never married_male_hispanic_.json",
"2.0_high school_never married_male_hispanic_.json",
"0.0_associates-vocational_never married_female_other non-hispanic_.json",
"1.0_less than 12th grade_widowed or divorced_female_hispanic_.json",
"2.0_grad school_married, spouse present_male_white non-hispanic_.json",
"1.0_high school_widowed or divorced_female_hispanic_.json",
"0.0_bachelors_separated_female_hispanic_.json",
"0.0_bachelors_separated_female_other non-hispanic_.json",
"1.0_some college, no degree_never married_female_other non-hispanic_.json",
"2.0_high school_married, spouse present_female_black non-hispanic_.json",
"0.0_associates-vocational_widowed or divorced_female_other non-hispanic_.json",
"1.0_less than 12th grade_widowed or divorced_male_white non-hispanic_.json",
"1.0_less than 12th grade_married, spouse present_male_other non-hispanic_.json",
"3.0_high school_never married_female_black non-hispanic_.json",
"2.0_high school_married, spouse present_male_other non-hispanic_.json",
"0.0_bachelors_separated_male_other non-hispanic_.json",
"0.0_less than 12th grade_separated_male_other non-hispanic_.json",
"0.0_associates-vocational_separated_female_black non-hispanic_.json",
"1.0_bachelors_married, spouse present_male_other non-hispanic_.json",
"2.0_less than 12th grade_never married_male_black non-hispanic_.json",
"1.0_grad school_married, spouse present_female_other non-hispanic_.json",
"1.0_less than 12th grade_separated_female_white non-hispanic_.json",
"1.0_high school_separated_male_white non-hispanic_.json",
"0.0_some college, no degree_separated_male_other non-hispanic_.json",
"1.0_bachelors_never married_female_white non-hispanic_.json",
"1.0_less than 12th grade_married, spouse present_male_black non-hispanic_.json",
"1.0_bachelors_married, spouse present_female_black non-hispanic_.json",
"1.0_some college, no degree_married, spouse present_female_other non-hispanic_.json",
"2.0_high school_separated_female_white non-hispanic_.json",
"1.0_bachelors_widowed or divorced_female_white non-hispanic_.json",
"0.0_grad school_widowed or divorced_female_hispanic_.json",
"2.0_associates-academic_married, spouse present_female_white non-hispanic_.json",
"1.0_some college, no degree_widowed or divorced_male_white non-hispanic_.json",
"0.0_grad school_widowed or divorced_male_other non-hispanic_.json",
"0.0_associates-academic_separated_female_black non-hispanic_.json",
"1.0_some college, no degree_married, spouse present_male_other non-hispanic_.json",
"2.0_some college, no degree_married, spouse present_female_hispanic_.json",
"1.0_some college, no degree_widowed or divorced_female_black non-hispanic_.json",
"2.0_high school_married, spouse present_female_other non-hispanic_.json",
"1.0_less than 12th grade_married, spouse present_female_other non-hispanic_.json",
"1.0_associates-vocational_never married_female_white non-hispanic_.json",
"3.0_high school_married, spouse present_female_white non-hispanic_.json",
"3.0_high school_married, spouse present_male_white non-hispanic_.json",
"1.0_some college, no degree_separated_female_black non-hispanic_.json",
"2.0_some college, no degree_widowed or divorced_female_white non-hispanic_.json",
"2.0_associates-vocational_married, spouse present_female_white non-hispanic_.json",
"2.0_less than 12th grade_separated_female_hispanic_.json",
"2.0_high school_never married_male_other non-hispanic_.json",
"1.0_bachelors_never married_female_black non-hispanic_.json",
"1.0_less than 12th grade_married, spouse present_female_black non-hispanic_.json",
"2.0_some college, no degree_married, spouse present_female_black non-hispanic_.json",
"1.0_associates-vocational_widowed or divorced_female_white non-hispanic_.json",
"2.0_high school_widowed or divorced_male_white non-hispanic_.json",
"2.0_high school_never married_female_other non-hispanic_.json",
"0.0_associates-academic_married, armed forces spouse present_female_white non-hispanic_.json",
"3.0_high school_never married_female_white non-hispanic_.json",
"1.0_grad school_married, spouse present_male_other non-hispanic_.json",
"3.0_less than 12th grade_never married_female_black non-hispanic_.json",
"2.0_some college, no degree_never married_male_white non-hispanic_.json",
"1.0_associates-vocational_never married_female_black non-hispanic_.json",
"1.0_bachelors_married, spouse present_male_black non-hispanic_.json",
"1.0_associates-academic_never married_female_white non-hispanic_.json",
"1.0_some college, no degree_widowed or divorced_female_hispanic_.json",
"0.0_associates-vocational_widowed or divorced_male_other non-hispanic_.json",
"0.0_associates-academic_widowed or divorced_male_hispanic_.json",
"1.0_associates-academic_widowed or divorced_female_white non-hispanic_.json",
"0.0_bachelors_separated_male_hispanic_.json",
"0.0_grad school_separated_female_black non-hispanic_.json",
"2.0_some college, no degree_never married_female_hispanic_.json",
"1.0_less than 12th grade_separated_female_black non-hispanic_.json",
"0.0_grad school_married, armed forces spouse present_female_white non-hispanic_.json",
"1.0_less than 12th grade_widowed or divorced_female_black non-hispanic_.json",
"1.0_high school_widowed or divorced_female_other non-hispanic_.json",
"2.0_less than 12th grade_never married_male_other non-hispanic_.json",
"2.0_bachelors_married, spouse present_female_other non-hispanic_.json",
"1.0_some college, no degree_never married_male_other non-hispanic_.json",
"1.0_high school_widowed or divorced_male_black non-hispanic_.json",
"2.0_some college, no degree_separated_female_white non-hispanic_.json",
"0.0_grad school_widowed or divorced_male_hispanic_.json",
"3.0_less than 12th grade_married, spouse present_female_hispanic_.json"]