var keysDict = {
    "absrsn94":[ "On layoff","Slack work/business conditions","Waiting for job to start","Vacation/personal days",
    "Illness/medical","Child care problems","Other family/personal obligation",
    "Parental leave","Labor dispute","Bad weather","School/training","Civic/military duty","Does not work in the business","Other"],
    "female76":["Female","Male"],
    "mlr76":["Employed","Unemployed","Not in labor force"],
    "employer89":["Private","Government","SE-incorporated","SE-unincorporated","Worked without pay"],
    "educ92":["Less than 12th grade","High School","Some college, no degree","Associates-vocational","Associates-academic","Bachelors","Grad school"],
    "marstat76":["Married, spouse present","Married, armed forces spouse present",
    "Separated","Widowed or divorced","Never married"],
    "raceeth76":["White non-Hispanic","Black non-Hispanic","Other non-Hispanic","Hispanic"],
    "race76":["White","Black","Other"],
    "uscitizen94":["Native","Foreign born, U.S. citizen","Foreign born, not U.S. citizen"],
    "industry76":["Mining","Constr","Manuf","Trade","Trans/Warehous/Util","Info","Finance","Prof/Biz Srvcs","Educ/Health","Leisure/Hosp","Other Srvcs","Public Admin","Ag"],
    "lfdetail94":["Unemployed less than 5 weeks","Unemployed 5-14 weeks","Unemployed 15-26 weeks",
        "Unemployed 27-51 weeks","Unemployed 52 or more weeks","FT(UFT)","FT(UPT)","UFT - Not at work",
        "PTNER(UFT) - Holiday","PTNER(UFT) - Labor dispute","PTNER(UFT) - Bad weather","PTNER(UFT) - Health/medical",
        "PTNER(UFT) - Vacation/personal day","PTNER(UFT) - Childcare","PTNER(UFT) - Family/personal obligation",
        "PTNER(UFT) - School/training","PTNER(UFT) - Other","PTER(UFT)- Slack work/business conditions",
        "PTER(UFT) - Seasonal work","PTER(UFT) - Job started/ended during week","PTER(UPT) - Slack work/business conditions", 
        "PTER(UPT) - Could only find part-time work","PTER(UPT) - Seasonal work",
        "PTNER(UPT) - PTER reason, but presumably unavail to work","PTNER(UPT) - Childcare",
        "PTNER(UPT) - Family/personal obligations","PTNER(UPT) - Health/medical",
        "PTNER(UPT) - School/training","PTNER(UPT) - Retired/Social Security limit on earnings",
        "PTNER(UPT) - FT workweek <35 hrs","PTNER(UPT) - Other","PTNER(UPT) - Not at work",
        "Not in labor force"
        ],
    "occupation76":["Managers","Professionals","Technicians",
        "Sales","Office and admin","Production, craft and repair",
        "Operators, fabricators and laborers","Protective service",
        "Food prep, buildings and grounds, cleaning","Personal care and personal services",
        "Agriculture"
        ],
    "metsize85":["Nonmetro or not identified",".1M-.25M",".25M-.5M",
        ".5M-1M","1M-2.5M","2.5M-5M",">5M"],
    "censusdiv76":["Pacific","East South Central","West South Central","Mountain",
        "New England","South Atlantic","West North Central", "East Noth Central","Mid Atlantic"],
        "numkidsundersix82":["0","1","2","3","4","5","6"]
}